name: Update Chart
on:  
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  Generate-Svgs:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn install

      - name: Build Chart
        run: yarn chart

      - name: Publish
        run: git add . && git commit . -m 'update' && git push
