name: Update Chart
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  Deploy-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn install

      - name: Build Chart
        run: yarn chart

      - name: Publish
        run: git push
