# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo github.repository.name
